area:
  - extension
  - hook
  - indexing
  - release
  - server
  - vef

kind:
  - bug
  - cleanup
  - documentation
  - epic
  - feature
  - regression
  - test

priority:
  - backlog
  - critical-urgent
  - important-longterm
  - important-soon
